replicaCount: 3

image:
  repository: verana/verana-visualizer
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: verana-visualizer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_ENDPOINT: "https://api.testnet.verana.network"
  NEXT_PUBLIC_RPC_ENDPOINT: "https://rpc.testnet.verana.network"
  NEXT_PUBLIC_IDX_ENDPOINT: "https://idx.testnet.verana.network"
  NEXT_PUBLIC_RESOLVER_ENDPOINT: "https://resolver.testnet.verana.network"
  NEXT_PUBLIC_CHAIN_ID: "vna-testnet-1"
  NEXT_PUBLIC_CHAIN_NAME: "Testnet"
  NEXT_PUBLIC_APP_NAME: "Verana Visualizer"
  NEXT_PUBLIC_APP_LOGO: "logo.svg"
